#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: scripts/test [OPTION...]
    Build and run services.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
cd ./aircraft-tracking && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./aircraft-cache && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./aircraft-web && \
  git checkout main && \
  git pull
